const ID_1_WIDTH_MM = 53.98;
const ID_1_HEIGHT_MM = 85.6;

export const ID_1_PORTRAIT_RATIO = ID_1_WIDTH_MM / ID_1_HEIGHT_MM;

export const WORKFLOW_NODE_CARD_WIDTH_PX = 121;
export const WORKFLOW_NODE_CARD_HEIGHT_PX = 192;

export const WORKFLOW_NODE_CARD_ASPECT_RATIO =
  WORKFLOW_NODE_CARD_WIDTH_PX / WORKFLOW_NODE_CARD_HEIGHT_PX;

export const WORKFLOW_NODE_CARD_SIZE_CLASSNAME =
  "h-[192px] w-[121px]" as const;
