"""Hosted Apps domain primitives independent of the backend transport."""

from orcheo.hosted_apps.auth import (
    AppAuthError,
    AppAuthService,
    IssuedAppSession,
    pkce_challenge,
)
from orcheo.hosted_apps.bundle_store import (
    AppBundleStore,
    FilesystemBundleStore,
    S3BundleStore,
)
from orcheo.hosted_apps.config import HostedAppsSettings, HostedAppsSettingsError
from orcheo.hosted_apps.data import AppDataConflictError, AppDataService, AppRecord
from orcheo.hosted_apps.deployments import DeploymentService, UploadNotFoundError
from orcheo.hosted_apps.errors import (
    AliasConflictError,
    AliasTombstonedError,
    AliasValidationError,
    BundleValidationError,
    HostedAppError,
    HostedAppsDisabledError,
    ReservedAliasError,
)
from orcheo.hosted_apps.gateway import (
    canonical_app_host,
    derive_client_ip,
    is_safe_app_path,
)
from orcheo.hosted_apps.governance import (
    OPERATION_POLICY,
    QuotaExceededError,
    QuotaLeaseManager,
)
from orcheo.hosted_apps.models import (
    DEFAULT_RESERVED_ALIASES,
    AppAlias,
    AppBinding,
    AppCollection,
    AppDeployment,
    AppRelease,
    AppRuntimeRun,
    AppSession,
    AppUpload,
    AppVisibility,
    AuthorizationCode,
    BundleFile,
    BundleManifest,
    DeploymentStatus,
    DispatchOutbox,
    HostedApp,
    IdempotencyRecord,
    LoginTransaction,
    ModerationBlock,
    PlatformAuditEvent,
    PublicationState,
    QuotaLease,
    RuntimeGeneration,
    normalize_alias,
    normalize_logical_name,
)
from orcheo.hosted_apps.repository import (
    HostedAppsRepository,
    InMemoryHostedAppsRepository,
)
from orcheo.hosted_apps.runtime import (
    AppRuntimeConflictError,
    AppRuntimeError,
    AppRuntimeResult,
    AppRuntimeService,
    validate_input_schema,
)


__all__ = [
    "AliasConflictError",
    "AliasTombstonedError",
    "AliasValidationError",
    "AppAlias",
    "AppAuthError",
    "AppAuthService",
    "AppBinding",
    "AppBundleStore",
    "AppCollection",
    "AppDataConflictError",
    "AppDataService",
    "AppDeployment",
    "AppRelease",
    "AppRuntimeRun",
    "AppRuntimeConflictError",
    "AppRuntimeError",
    "AppRuntimeResult",
    "AppRuntimeService",
    "AppRecord",
    "AppSession",
    "AppUpload",
    "AppVisibility",
    "AuthorizationCode",
    "BundleFile",
    "BundleManifest",
    "BundleValidationError",
    "canonical_app_host",
    "derive_client_ip",
    "DEFAULT_RESERVED_ALIASES",
    "DeploymentService",
    "DeploymentStatus",
    "DispatchOutbox",
    "FilesystemBundleStore",
    "HostedApp",
    "HostedAppError",
    "HostedAppsSettings",
    "HostedAppsSettingsError",
    "HostedAppsRepository",
    "InMemoryHostedAppsRepository",
    "is_safe_app_path",
    "HostedAppsDisabledError",
    "IdempotencyRecord",
    "IssuedAppSession",
    "LoginTransaction",
    "ModerationBlock",
    "OPERATION_POLICY",
    "PlatformAuditEvent",
    "pkce_challenge",
    "PublicationState",
    "QuotaLease",
    "QuotaExceededError",
    "QuotaLeaseManager",
    "ReservedAliasError",
    "RuntimeGeneration",
    "S3BundleStore",
    "UploadNotFoundError",
    "normalize_alias",
    "normalize_logical_name",
    "validate_input_schema",
]
