"""Reusable qualitative-analysis nodes, models, and helpers.

This package generalises the nodes and edges originally written inline in the
Theme Analyst, Theme Coding Analyst, and Insight Reporter colleague workflows.
Each workflow specialises the shared nodes purely through init arguments (result
key wiring, prompt templates, classification modes, and messages).
"""

from __future__ import annotations
from orcheo.nodes.qualitative.accessors import (
    build_report_data,
    get_approved_codebook,
    get_approved_insight_ids,
    get_candidate_insights,
    get_code_assignments,
    get_configurable,
    get_cooccurrence,
    get_draft_codebook,
    get_pending_documents,
    get_quality_report,
    get_quantification,
    get_recommendations,
    get_research_objective,
    get_seed_codebook_from_file,
    get_segment_breakdowns,
    get_segment_comparisons,
    get_selected_quotes,
    get_source_payload,
    get_units,
    is_vacuous,
)
from orcheo.nodes.qualitative.codebook import (
    code_to_theme_map,
    escape_markdown_table_cell,
    fallback_codebook,
    get_seed_codebook,
    make_code_id,
    make_insight_id,
    make_theme_id,
    make_unit_id,
    merge_codebooks,
    normalise_codebook_ids,
    normalise_label,
    parse_codebook_csv,
    parse_codebook_markdown,
    parse_markdown_table_row,
    recover_exportable_codebook,
    render_codebook_for_prompt,
)
from orcheo.nodes.qualitative.coded_data import (
    CODED_DATA_CSV_HEADERS,
    build_coded_data_csv,
    parse_coded_data_csv,
)
from orcheo.nodes.qualitative.coding import (
    batch_units,
    existing_code_hints,
    filter_assignments_to_codebook,
    format_assignments_with_units,
    format_open_coding_user_text,
    format_recoding_user_text,
    with_inferred_sentiment,
)
from orcheo.nodes.qualitative.constants import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_PER_TURN_BATCH_BUDGET,
    DEFAULT_QUOTES_PER_THEME,
    MAX_CODING_BATCHES,
    OPEN_CODING_RECURSION_LIMIT,
    RECODING_RECURSION_LIMIT,
)
from orcheo.nodes.qualitative.insights import (
    InsightCriticNode,
    RecommendationGeneratorNode,
    critique_insights,
    fallback_insights,
    fallback_quotes,
    filter_grounded_quotes,
    normalise_candidate_insights,
    recommend_action,
    recommend_impact,
)
from orcheo.nodes.qualitative.keys import QualitativeResultKeys
from orcheo.nodes.qualitative.models import (
    CandidateInsight,
    CodeAssignment,
    CodeAssignmentEntry,
    Codebook,
    CodebookConsolidationResponse,
    CooccurrenceRow,
    Insight,
    InsightGenerationResponse,
    OpenCodingBatchResponse,
    ParsedRecord,
    QualityFlagSummary,
    QualityReport,
    QuantificationRow,
    Quote,
    QuoteSelectionResponse,
    RecodingBatchResponse,
    Recommendation,
    ReportData,
    SegmentBreakdownRow,
    SegmentComparison,
    SegmentVariable,
    Subtheme,
    Theme,
    Unit,
)
from orcheo.nodes.qualitative.pipeline import (
    CodebookOutputNode,
    ContextPreNode,
    ExportCodebookNode,
    ExportCodedDataNode,
    FileValidatorNode,
    IngestNode,
    RecodeOutputNode,
    SetupNode,
)
from orcheo.nodes.qualitative.quality import (
    DataQualityNode,
    assess_quality,
)
from orcheo.nodes.qualitative.quantify import (
    CodedDataIngestNode,
    compare_segments,
    compute_quantification,
    compute_segment_breakdowns,
    parse_str_list,
    plan_segments,
)
from orcheo.nodes.qualitative.report import (
    ExportReportNode,
    ReportOutputNode,
    render_markdown_report,
    validate_final_state,
)
from orcheo.nodes.qualitative.sources import (
    SourceParser,
    pick_id_field,
    pick_text_field,
)
from orcheo.nodes.qualitative.stages import (
    LLMStageFinalizeNode,
    LLMStagePrepareNode,
)


__all__ = [
    # constants
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_PER_TURN_BATCH_BUDGET",
    "DEFAULT_QUOTES_PER_THEME",
    "MAX_CODING_BATCHES",
    "OPEN_CODING_RECURSION_LIMIT",
    "RECODING_RECURSION_LIMIT",
    # keys
    "QualitativeResultKeys",
    # models
    "CandidateInsight",
    "CodeAssignment",
    "CodeAssignmentEntry",
    "Codebook",
    "CodebookConsolidationResponse",
    "CooccurrenceRow",
    "Insight",
    "InsightGenerationResponse",
    "OpenCodingBatchResponse",
    "ParsedRecord",
    "QualityFlagSummary",
    "QualityReport",
    "QuantificationRow",
    "Quote",
    "QuoteSelectionResponse",
    "Recommendation",
    "RecodingBatchResponse",
    "ReportData",
    "SegmentBreakdownRow",
    "SegmentComparison",
    "SegmentVariable",
    "Subtheme",
    "Theme",
    "Unit",
    # accessors
    "build_report_data",
    "get_approved_codebook",
    "get_approved_insight_ids",
    "get_candidate_insights",
    "get_code_assignments",
    "get_configurable",
    "get_cooccurrence",
    "get_draft_codebook",
    "get_pending_documents",
    "get_quality_report",
    "get_quantification",
    "get_recommendations",
    "get_research_objective",
    "get_seed_codebook",
    "get_seed_codebook_from_file",
    "get_segment_breakdowns",
    "get_segment_comparisons",
    "get_selected_quotes",
    "get_source_payload",
    "get_units",
    "is_vacuous",
    # sources
    "SourceParser",
    "pick_id_field",
    "pick_text_field",
    # codebook
    "code_to_theme_map",
    "escape_markdown_table_cell",
    "fallback_codebook",
    "make_code_id",
    "make_insight_id",
    "make_theme_id",
    "make_unit_id",
    "merge_codebooks",
    "normalise_codebook_ids",
    "normalise_label",
    "parse_codebook_csv",
    "parse_codebook_markdown",
    "parse_markdown_table_row",
    "recover_exportable_codebook",
    "render_codebook_for_prompt",
    # coding
    "batch_units",
    "existing_code_hints",
    "filter_assignments_to_codebook",
    "format_assignments_with_units",
    "format_open_coding_user_text",
    "format_recoding_user_text",
    "with_inferred_sentiment",
    # coded data
    "CODED_DATA_CSV_HEADERS",
    "build_coded_data_csv",
    "parse_coded_data_csv",
    # quality
    "DataQualityNode",
    "assess_quality",
    # quantify
    "CodedDataIngestNode",
    "compare_segments",
    "compute_quantification",
    "compute_segment_breakdowns",
    "parse_str_list",
    "plan_segments",
    # insights
    "InsightCriticNode",
    "RecommendationGeneratorNode",
    "critique_insights",
    "fallback_insights",
    "fallback_quotes",
    "filter_grounded_quotes",
    "normalise_candidate_insights",
    "recommend_action",
    "recommend_impact",
    # report
    "ExportReportNode",
    "ReportOutputNode",
    "render_markdown_report",
    "validate_final_state",
    # stages
    "LLMStageFinalizeNode",
    "LLMStagePrepareNode",
    # pipeline
    "CodebookOutputNode",
    "ContextPreNode",
    "ExportCodebookNode",
    "ExportCodedDataNode",
    "FileValidatorNode",
    "IngestNode",
    "RecodeOutputNode",
    "SetupNode",
]
